### ISSUE TITLE
An inplace operation in the forward process

### ISSUE THREAD

**Issue by VanderHua** [thuanz123/enhancing-transformers#11]
Hi, 

I found an inplace operation in the forward process of ViTDecoder:
https://github.com/thuanz123/enhancing-transformers/blob/b1bdeaf87cc78cc3aeb20d1312439423a35a52fd/enhancing/modules/stage1/layers.py#L210
which may cause the error: 
`RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation`
 

This error can occur in such use cases:
```
decoder_a = ViTDecoder(**decoder_config_a)
decoder_b = ViTDecoder(**decoder_config_b)
rec_a = decoder_a(quant)
rec_b = decoder_b(quant)        # Above error will occur when backwarding, as the quant is modified by the above inplace operation here
```

Maybe it would be better to change it to:
`token = token + self.de_pos_embedding`

P.S. Perhaps this operation also occurs elsewhere, I did not double-check other places.

**Comment by thuanz123** [comment]
Hi @VanderHua, sorry for late reply. Thank you for catching this. It should be good now.
