### ISSUE TITLE
stage2 transformer

### ISSUE THREAD

**Issue by Mdahao** [thuanz123/enhancing-transformers#13]
hi @manuelknott, the code for stage2 transformer is currently buggy so after I fixed everything, I will try to train and released a pretrained model. But this will be a long time later since I'm still learning about autoregressive modeling with transformers.

_Originally posted by @thuanz123 in https://github.com/thuanz123/enhancing-transformers/issues/8#issuecomment-1236247589_
            
Hi, I'm sorry to bother you. Has this pre-trained model been released?

**Comment by thuanz123** [comment]
Hi, unfortunately, training the stage 2 model requires a large computational budget so that there will be no pretrained weight for stage 2 model

**Comment by thuanz123** [comment]
If you dont have any further question, I will close this issue. Feel free to re-open it and/or ask any more questions
