### ISSUE TITLE
Model license

### ISSUE THREAD

**Issue by Aspie96** [thuanz123/enhancing-transformers#15]
Hi.

I am aware of the fact that the repository itself is under the MIT license.

Since the models are external to the repository, if you trained the models from scratch, would you consider specifying a license for the trained models (or specify that the license applies to the models too)?

**Comment by thuanz123** [comment]
Hi @Aspie96,  I never thought about this license for model thing 👍 and I think MIT License is also cover the weight of the model too, right?

**Comment by Aspie96** [comment]
I am not a lawyer and this is not legal advice.

> Hi @Aspie96, I never thought about this license for model thing 👍 and I think MIT License is also cover the weight of the model too, right?

As is, this is not specified in the repo, so I wouldn't personally have relied on this assumption prior to your reply. But obviously it's your choice, and from your answer it seems to be your intention that it should.

I presumed that by "Distributed under the MIT License" you referred to both the repository as well as the model checkpoints. In which case, feel free to close this issue (although I'd still encourage clarifying it in the README.

May I ask you if you trained the models from scratch?

Thank you very much!

**Comment by thuanz123** [comment]
Thanks. I will make it clear in the REaDME. Also, the weights are trained from scratch

**Comment by Aspie96** [comment]
Thank you, that is awesome!
